In [2]:
import pandas as pd

from sklearn.model_selection import train_test_split

In [3]:
X_df = pd.read_csv(r"..\dataset_updated\book30-listing-train.csv", 
                   names=["amazon_index_asin", "filename", "image_url", "title", "author", "category_id", "category"],
                   index_col="filename")

In [4]:
X_df.head()

,amazon_index_asin,image_url,title,author,category_id,category
filename,,,,,,
1588345297.jpg,1588345297,http://ecx.images-amazon.com/images/I/51l6XIoa...,With Schwarzkopf: Life Lessons of The Bear,Gus Lee,1,Biographies & Memoirs
1404803335.jpg,1404803335,http://ecx.images-amazon.com/images/I/51UJnL3T...,"Magnets: Pulling Together, Pushing Apart (Amaz...",Natalie M. Rosinsky,4,Children's Books
1446276082.jpg,1446276082,http://ecx.images-amazon.com/images/I/51MGUKhk...,Energy Security (SAGE Library of International...,NaN,10,Engineering & Transportation
1491522666.jpg,1491522666,http://ecx.images-amazon.com/images/I/51qKvjsi...,An Amish Gathering: Life in Lancaster County,Beth Wiseman,9,Christian Books & Bibles
0970096410.jpg,970096410,http://ecx.images-amazon.com/images/I/51qoUENb...,City of Rocks Idaho: A Climber's Guide (Region...,Dave Bingham,26,Sports & Outdoors

In [5]:
X_df.describe()

        category_id
count  51300.000000
mean      14.500000
std        8.655526
min        0.000000
25%        7.000000
50%       14.500000
75%       22.000000
max       29.000000

In [6]:
X_df.info()

<class 'pandas.DataFrame'>
Index: 51300 entries, 1588345297.jpg to 045147483X.jpg
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amazon_index_asin  51300 non-null  str
 1   image_url          51300 non-null  str
 2   title              51300 non-null  str
 3   author             47861 non-null  str
 4   category_id        51300 non-null  int64
 5   category           51300 non-null  str
dtypes: int64(1), str(5)
memory usage: 2.7+ MB

In [8]:
y_df = pd.read_csv(r"..\dataset_updated\bookcover30-labels-train.txt",
                   sep=" ",
                   names=["filename", "category_id"],
                   index_col="filename")

In [9]:
y_df.head()

                category_id
filename
1588345297.jpg            1
1404803335.jpg            4
1446276082.jpg           10
1491522666.jpg            9
0970096410.jpg           26

In [10]:
y_df.describe()

        category_id
count  51300.000000
mean      14.500000
std        8.655526
min        0.000000
25%        7.000000
50%       14.500000
75%       22.000000
max       29.000000

In [12]:
y_df.info()

<class 'pandas.DataFrame'>
Index: 51300 entries, 1588345297.jpg to 045147483X.jpg
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   category_id  51300 non-null  int64
dtypes: int64(1)
memory usage: 801.6+ KB

In [13]:
X_train, X_val, y_train, y_val = train_test_split(X_df, y_df, test_size=(1/9), random_state=42, stratify=y_df)

In [14]:
# Check if the split is stratified

y_df.value_counts(normalize="True")

category_id
1              0.033333
4              0.033333
10             0.033333
9              0.033333
26             0.033333
11             0.033333
16             0.033333
23             0.033333
29             0.033333
2              0.033333
7              0.033333
19             0.033333
8              0.033333
21             0.033333
15             0.033333
13             0.033333
14             0.033333
6              0.033333
28             0.033333
0              0.033333
18             0.033333
22             0.033333
12             0.033333
5              0.033333
20             0.033333
27             0.033333
25             0.033333
3              0.033333
24             0.033333
17             0.033333
Name: proportion, dtype: float64

In [15]:
y_train.value_counts(normalize="True")

category_id
22             0.033333
2              0.033333
7              0.033333
20             0.033333
21             0.033333
3              0.033333
28             0.033333
5              0.033333
8              0.033333
0              0.033333
12             0.033333
19             0.033333
26             0.033333
1              0.033333
10             0.033333
9              0.033333
18             0.033333
23             0.033333
11             0.033333
4              0.033333
6              0.033333
14             0.033333
24             0.033333
25             0.033333
17             0.033333
13             0.033333
27             0.033333
29             0.033333
15             0.033333
16             0.033333
Name: proportion, dtype: float64

In [16]:
y_val.value_counts(normalize="True")

category_id
18             0.033333
6              0.033333
25             0.033333
7              0.033333
5              0.033333
29             0.033333
23             0.033333
21             0.033333
19             0.033333
4              0.033333
20             0.033333
26             0.033333
15             0.033333
24             0.033333
2              0.033333
3              0.033333
9              0.033333
13             0.033333
16             0.033333
17             0.033333
12             0.033333
0              0.033333
22             0.033333
8              0.033333
1              0.033333
14             0.033333
27             0.033333
10             0.033333
11             0.033333
28             0.033333
Name: proportion, dtype: float64

In [17]:
y_val

                category_id
filename
0544279328.jpg           18
0801887186.jpg           18
1634594525.jpg            6
0872204022.jpg           25
0962781037.jpg            7
...                     ...
1586489534.jpg            2
0880113146.jpg           26
B004RSFXUI.jpg           26
0805099247.jpg           27
1118061608.jpg           10

[5700 rows x 1 columns]

In [ ]:
train_folder_path = r"..\dataset_updated\train"
val_folder_path = r"..\dataset_updated\validation"
test_folder_path = r"..\dataset_updated\test"

In [21]:
X_train.to_csv(train_folder_path+"/listings_train.csv")
y_train.to_csv(train_folder_path+"/labels_train.csv")

In [22]:
X_val.to_csv(val_folder_path+"/listings_val.csv")
y_val.to_csv(val_folder_path+"/labels_val.csv")

In [23]:
X_test = pd.read_csv(r"C:\Users\Neil\Documents\Personal\dlsu\computer_vision\CSC930M-Project1\dataset_updated\book30-listing-test.csv", 
                   names=["amazon_index_asin", "filename", "image_url", "title", "author", "category_id", "category"],
                   index_col="filename")

y_test = pd.read_csv(r"C:\Users\Neil\Documents\Personal\dlsu\computer_vision\CSC930M-Project1\dataset_updated\bookcover30-labels-train.txt",
                   sep=" ",
                   names=["filename", "category_id"],
                   index_col="filename")

In [24]:
X_test.to_csv(test_folder_path+"/X_test.csv")
y_test.to_csv(test_folder_path+"/y_test.csv")